Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job                       count    min threads    max threads
----------------------  -------  -------------  -------------
all                           1              1              1
prepare_files_and_dirs        3              1              1
run_PDBminer                  3              1              1
total                         7              1              1

Select jobs to execute...

[Wed Oct  5 15:47:13 2022]
rule prepare_files_and_dirs:
    input: /data/user/krde/PDBminer/examples/input_file
    output: /data/user/krde/PDBminer/examples/input_file/results/P0A7Y7/P0A7Y7_input.csv
    jobid: 2
    wildcards: path=/data/user/krde/PDBminer/examples/input_file, uniprot_id=P0A7Y7
    resources: tmpdir=/tmp

[Wed Oct  5 15:47:14 2022]
Finished job 2.
1 of 7 steps (14%) done
Select jobs to execute...

[Wed Oct  5 15:47:14 2022]
rule prepare_files_and_dirs:
    input: /data/user/krde/PDBminer/examples/input_file
    output: /data/user/krde/PDBminer/examples/input_file/results/P11532/P11532_input.csv
    jobid: 6
    wildcards: path=/data/user/krde/PDBminer/examples/input_file, uniprot_id=P11532
    resources: tmpdir=/tmp

[Wed Oct  5 15:47:15 2022]
Finished job 6.
2 of 7 steps (29%) done
Select jobs to execute...

[Wed Oct  5 15:47:15 2022]
rule run_PDBminer:
    input: /data/user/krde/PDBminer/examples/input_file/results/P11532/P11532_input.csv
    output: /data/user/krde/PDBminer/examples/input_file/results/P11532/P11532_done.txt
    jobid: 5
    wildcards: path=/data/user/krde/PDBminer/examples/input_file, uniprot_id=P11532
    resources: tmpdir=/tmp

[Wed Oct  5 15:47:32 2022]
Error in rule run_PDBminer:
    jobid: 5
    output: /data/user/krde/PDBminer/examples/input_file/results/P11532/P11532_done.txt

RuleException:
CalledProcessError in line 98 of /data/user/krde/PDBminer/examples/input_file/program/snakefile:
Command 'set -euo pipefail;  /home/krde/.conda/envs/PDBminer/bin/python3.8 /data/user/krde/PDBminer/examples/input_file/program/.snakemake/scripts/tmpsgceunrf.PDBminer_run.py' returned non-zero exit status 1.
  File "/data/user/krde/PDBminer/examples/input_file/program/snakefile", line 98, in __rule_run_PDBminer
  File "/home/krde/.conda/envs/PDBminer/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-10-05T154712.733966.snakemake.log
